def welcome_notification_func():
    ...

def verified_notification_func():
    ...

def user_update_notification_func():
    ...

def order_create_notification_func():
    ...

def order_on_ship_notification_func():
    ...

def order_on_way_notification_func():
    ...

def order_cancelled_notification_func():
    ...

def back_order_notification_func():
    ...

def order_arrive_notification_func():
    ...

def payment_received_notification_func():
    ...

def payment_failed_notification_func():
    ...
